### ISSUE TITLE
Question. Setup is not pretty clear.

### ISSUE THREAD

**Issue by DaggLo** [arnaud-dezandee/fast-eslint#274]
Hi!

I can't fully figure out the installation process. As far as I've got I should at least  `apm install fast-eslint`.

After that was done I've got somehow working linter. But that was when I worked in a directory with a `.eslintrc.*` with defined `extends: airbnb-base` and other plugins and ESlint installed locally. But even then I wasn't sure if **fast-eslint** was using config specified  in the `.eslintrc.*`.

After that I went to another dir with no npm-packages and configs installed (clear directory with only text files) and restart Atom. And in that case the **fast-eslint** plugin didn't work (I guess it couldn't get a config file).

At that point my question is what are certain steps to get this plugin work from any place in my system?
- Should I mandatory install a shared config globally?
- Should I mandatory install globally the ESlint package and other packages the shared config depends on?
- Should I mandatory create `.eslintrc.*` in my home or other directories?
- Should I mandatory configure my Atom via `Atom` -> `Config...` specifying `baseConfigExtends` property? 

Is it all mandatory or something is optional?

And one more thing - how can I make sure the **fast-eslint** is using a right config?

Thank you!

**Comment by arnaud-dezandee** [comment]
Hi @DaggLo,

- If you want ESLint work on any `.js` files you open with Atom, you need a global config file or `baseConfigExtends`. Home directory allows for more customization.
- ESLint main package is included with the plugin. However if your global config needs plugins, you need to install them globally too.
- If the project directory contains its own `eslintrc` file, this file (and plugins and so on) will be used instead
- You can use `baseConfigExtends` instead of a home dir config file if you prefer that. Specified base configs still needs to be installed either in the current project dir or globally.

Cheers

**Comment by DaggLo** [comment]
Thanks!
This was helpful.
